### ISSUE TITLE
Errors bij eerste keer runnen

### ISSUE THREAD

**Issue by Geestig** [wearechilli/craft-starter#2]
- [x] Stap 1 van de craft-starter geeft het volgende terug:

```
Downloading https://github.com/wearechilli/craft-starter/archive/HEAD.zip ...
  … setting up project Error: unable to download https://github.com/wearechilli/craft-starter/archive/HEAD.zip. status: 404 
```

- [ ] In de env file mag je de / weglaten bij de primary site url aangezien hij anders niet correct de app.js inlaad.

- [x] Standaard werkt de hot reloading nog niet. (omdat hij geen changes waarneemt)

**Comment by stenvdb** [comment]
Het werkte niet omdat de repo nog op private stond.
